### ISSUE TITLE
Make a FuBar addon

### ISSUE THREAD

**Issue by waytoomuchgaming** [Road-block/CallToArms#3]
To avoid minimap button, while still having a way to click the addon.

**Comment by Road-block** [comment]
That's a good suggestion, I'll look at how involved it is.  
The problem is the CTA minimap icon has utility it's not just there for the options.. it can also show the filtered messages that CTA catches as a list of floating messages near the minimap.  
I'd have to look at Fubar to see if that's even possible and if it is, it need to be aware of where the panel is at (top of screen or bottom) etc.  
I'm not against this feature but don't expect it right away.

**Comment by Road-block** [comment]
https://github.com/Road-block/FuBar_CTAFu/releases/latest
